# Generated by Django 5.0.6 on 2024-07-23 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agthi', '0003_job_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_application',
            name='apl_rec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agthi.job_recruitment'),
        ),
    ]
