# Generated by Django 5.0.6 on 2024-07-31 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agthi', '0004_job_application_apl_rec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('name', models.CharField(max_length=200, null=True)),
                ('local_international', models.CharField(max_length=200, null=True)),
                ('brand_paragraph', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('img_resta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agthi.restaurants')),
            ],
        ),
    ]
