# Generated by Django 5.0.6 on 2024-08-01 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agthi', '0005_restaurants_restaurant_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_application',
            name='apl_rec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agthi.job_recruitment'),
        ),
        migrations.AlterField(
            model_name='restaurant_images',
            name='img_resta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agthi.restaurants'),
        ),
    ]
