# Generated by Django 5.0.6 on 2024-08-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agthi', '0007_restaurants_brand_paragraph1'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
