# Generated by Django 5.0.6 on 2024-08-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agthi', '0008_restaurants_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
