# Generated by Django 5.0.8 on 2024-08-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agthi', '0010_aboutt_latest_news_mission_our_people_vision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest_news',
            name='news_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
