# Generated by Django 5.0.8 on 2024-08-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agthi', '0015_alter_restaurants_facebook_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_uss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('place', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('instagram_link', models.URLField(default='https://www.instagram.com/')),
                ('facebook_link', models.URLField(default='https://www.facebook.com/')),
                ('twitter_link', models.URLField(default='https://www.twitter.com/')),
                ('pinterest_link', models.CharField(default='https://www.pinterest.com/', max_length=200)),
                ('contact_email', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
