# Generated by Django 5.0.8 on 2024-08-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agthi', '0016_contact_uss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_uss',
            name='facebook_link',
            field=models.URLField(default='https://www.facebook.com/', null=True),
        ),
        migrations.AlterField(
            model_name='contact_uss',
            name='instagram_link',
            field=models.URLField(default='https://www.instagram.com/', null=True),
        ),
        migrations.AlterField(
            model_name='contact_uss',
            name='pinterest_link',
            field=models.CharField(default='https://www.pinterest.com/', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact_uss',
            name='twitter_link',
            field=models.URLField(default='https://www.twitter.com/', null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='facebook_link',
            field=models.URLField(default='https://www.facebook.com/', null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='instagram_link',
            field=models.URLField(default='https://www.instagram.com/', null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='twitter_link',
            field=models.URLField(default='https://www.twitter.com/', null=True),
        ),
    ]
